### ISSUE TITLE
两点疑惑求解答

### ISSUE THREAD

**Issue by Eaphan** [Joryun/Shop#1]
1.数据库sql文件中为啥每个表没有主键
2.感觉packet表没啥用的样子，直接将优惠券ticket表中的packet_id变成uid也行，还是有别的用处我没看懂？
3.好像管理员登录界面进不去
新手求解释，谢谢！

**Comment by Javadp** [comment]
1.不知道为什么在eclipse中不能运行，在tomcat的webaaps中没用编译好的class文件，但是在项目的/target/classes中却存在对应类的class文件，不知道问题出在哪，能解释一下吗？谢谢！
