### ISSUE TITLE
JDK什么版本也不说，TOMCAT什么版本也不说，真他妈的浪费一晚上时间，垃圾！

### ISSUE THREAD

**Issue by ghost** [Joryun/Shop#5]
JDK什么版本也不说，TOMCAT什么版本也不说，真他妈的浪费一晚上时间，垃圾！

**Comment by liyang0211** [comment]
干你娘的！

**Comment by ghost** [comment]
真他妈的气！搞了五年JAVA就没遇见过你这么垃圾的项目！浪费劳资一晚上！干你娘啊！时间本来就紧张！草泥马比！放你妈比的GITHUB啊！干你全家！垃圾东西！
